networks:
  default:
    external:
      name: dy
services:
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
  odoo:
    build: odoo
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=db
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=demo
      - VIRTUAL_HOST=docky-11-oca-instance.dy
      - VIRTUAL_PORT=8069
      - ADDONS_PATH=src/addons,src/odoo/addons,links,local-src
      - GITHUB_LOGIN=XXXX
      - GITHUB_PASSWORD=XXXX
    links:
      - db
    networks:
      default:
        aliases:
          - docky-11-oca-instance.dy
    volumes:
      - ./odoo:/opt/odoo
      - ../oca_code_source:/oca_code_source
version: '3'
