networks:
  default:
    external:
      name: dy
services:
  odoo:
    build: odoo
    environment:
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=8069
      - LOCAL_USER_ID=$UID
      - DB_HOST=$PGHOST
      - DB_USER=$PGUSER
      - DB_PASSWORD=$PGPASSWORD
      - DB_NAME=$PGDATABASE
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=demo
    volumes:
      - ./odoo:/opt/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
version: '3'
